version: 0.2

env:
  variables:
    # This S3 stores the ECS Reference Architecture CloudFormation templates
    # so that they can be deployed via a button on the project GitHub README
    S3_BUCKET: "brdemo10"

phases:

  pre_build: 
    commands:

      # Validate all of the CloudFormation templates
      - chmod a+x ./tests/validate-templates.sh
      - ./tests/validate-templates.sh

  build:
    commands:
      - docker build --tag 124864831979.dkr.ecr.eu-west-3.amazonaws.com/ps:latest ./services/product-service/src/
      - docker build --tag 124864831979.dkr.ecr.eu-west-3.amazonaws.com/ws:latest ./services/website-service/src/
  post_build:
    commands:
      - docker push 124864831979.dkr.ecr.eu-west-3.amazonaws.com/ps
      - docker push 124864831979.dkr.ecr.eu-west-3.amazonaws.com/ws
      # Sync the templates
      # - aws s3 sync . s3://${S3_BUCKET}
      
artifacts:
  files:
    - master.yaml
  discard-path: yes
      
      
      

